version: '3'
services:
  vue-ui:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "80:8080"
    container_name: vue-ui
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
